### ISSUE TITLE
Bump lifecycle to 0.17.0

### ISSUE THREAD

**Issue by cmoulliard** [paketo-community/builder-ubi-base#9]
## Todo

As lifecycle 0.17.0 has been [released](https://github.com/buildpacks/lifecycle/releases/tag/v0.17.0), that paketo-jammy-builder image has been released too to package [it,](https://github.com/paketo-buildpacks/builder-jammy-tiny/releases/tag/v0.0.176), that should be great to bump the lifecycle version within the `builder.toml` and to release a new version

WDYT ?  @mhdawson

**Comment by BarDweller** [comment]
the workflow has already raised the PR for this https://github.com/paketo-community/builder-ubi-base/pull/6 (3 days ago), but it has yet to be reviewed/merged

**Comment by mhdawson** [comment]
This can now be closed as the lifecycle is update to 0.17.0 has already landed.
